package tests;// Generated by Selenium IDE

import base.MainTest;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class CheckDisabledElement extends MainTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/nemenne.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void CheckAllElementsEnabledDisabled() {
    driver.get(BASE_URL);
    Assert.assertFalse(driver.findElement(By.xpath("//*[@id=\"inputEmail3\"]")).isEnabled());
    Assert.assertFalse(driver.findElement(By.xpath("//*[@id=\"sel1\"]")).isEnabled());
    Assert.assertTrue(driver.findElement(By.xpath("//*[@id=\"sel2\"]")).isEnabled());
    Assert.assertFalse(driver.findElement(By.xpath("//*[@id=\"sel2\"]")).findElement(By.xpath("./option[1]")).isEnabled());
    Assert.assertFalse(driver.findElement(By.xpath("//*[@id=\"sel2\"]")).findElement(By.xpath("./option[2]")).isEnabled());
    Assert.assertTrue(driver.findElement(By.xpath("//*[@id=\"sel2\"]")).findElement(By.xpath("./option[3]")).isEnabled());
    Assert.assertFalse(driver.findElement(By.xpath("/html/body/div/div/div/div[4]/div/button[1]")).isEnabled());
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/div[4]/div/button[2]")).isEnabled());

  }
}

