// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class DonaldDragAndDrop {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/moveme.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void dragAndDropSucces() {
    driver.manage().window().maximize();

    driver.get(BASE_URL);
    WebElement donald = driver.findElement(By.id("donald"));
    WebElement finish = driver.findElement(By.id("tree"));
    Actions actions = new Actions(driver);

    actions.dragAndDrop(donald,finish).build().perform();
    String zvolani = driver.findElement(By.xpath("/html/body/div[2]/h2")).getText();
    Assert.assertEquals("HOOO HOOOOO !!!!",zvolani);
  }

  @Test
  public void dragAndDropFuckYouDonald() throws InterruptedException {
    driver.manage().window().maximize();
    driver.get(BASE_URL);
    WebElement donald = driver.findElement(By.id("donald"));
    Actions actions = new Actions(driver);
    //actions.clickAndHold(donald).moveByOffset(1300,0).release().build().perform();
    for (int i = 0; i < 40; i++) {
      actions.clickAndHold(donald).moveByOffset(33,0).release().build().perform();
      Thread.sleep(100);
    }
  }


  @After
  public void tearDown() throws IOException {
    //driver.close();
    //driver.quit();
  }
}
