// Generated by Selenium IDE

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class FailedScreenshot {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/vybersi.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void failedTest() {
    driver.get(BASE_URL);
    new Select(driver.findElement(By.xpath("/html/body/div/div[1]/select"))).selectByVisibleText("Pikachu");
    String actualTitle = driver.findElement(By.xpath("/html/body/div/div[2]/h3")).getText();
    Assert.assertTrue(actualTitle.contains("Pikachu"));

    new Select(driver.findElement(By.xpath("/html/body/div/div[1]/select"))).selectByVisibleText("Pikachu");
    actualTitle = driver.findElement(By.xpath("/html/body/div/div[2]/h3")).getText();
    Assert.assertTrue(actualTitle.contains("Charmander"));
  }

  @After
  public void tearDown() throws IOException {
    File screenShot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
    FileUtils.copyFileToDirectory(screenShot, new File("/Users/simonurych/IdeaProjects/SeleniumTutorialBasicJava18/Screenshots"));

    driver.close();
    driver.quit();
  }
}
