// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class MoveCursorAndHold {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/semafor.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void moveFocusClickAndVerifyColor() {
    String expectedOrange ="rgba(191, 111, 7, 1)";

    driver.get(BASE_URL);
    WebElement trafficLight = driver.findElement(By.className("light"));

    Actions actions = new Actions(driver);
    actions.clickAndHold(trafficLight).build().perform();
    String actualOrange = trafficLight.getCssValue("background-color");
    Assert.assertEquals(expectedOrange,actualOrange);
  }

  @Test
  public void moveFocusAndVerifyColor() {
    String expectedGreen = "rgba(10, 129, 0, 1)";
    String expectedRed = "rgba(205, 58, 63, 1)";

    driver.get(BASE_URL);
    WebElement trafficLight = driver.findElement(By.className("light"));
    String actualRedColor = trafficLight.getCssValue("background-color");
    Assert.assertEquals(expectedRed,actualRedColor);

    Actions actions = new Actions(driver);

    actions.moveToElement(trafficLight).build().perform();
    String actualGreenColor = trafficLight.getCssValue("background-color");
    Assert.assertEquals(expectedGreen,actualGreenColor);
  }

  @After
  public void tearDown() throws IOException {
    //driver.close();
    //driver.quit();
  }
}
