// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class NavigaceBackForwardRefresh {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/registracia.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void navigaceBack() throws InterruptedException {
    driver.get(BASE_URL);
    String email = "jsemdospelyclovek@nebudutadypsat.tvojemama";
    driver.findElement(By.name("email")).sendKeys(email);
    driver.findElement(By.xpath("/html/body/nav/div/ul/li[8]/a")).click();
    driver.navigate().back();
    new WebDriverWait(driver, Duration.ofSeconds(2)).until(ExpectedConditions.presenceOfElementLocated(By.name("email")));
    Assert.assertEquals(email,(driver.findElement(By.name("email")).getAttribute("value")));
  }

  @Test
  public void navigaceForward() throws InterruptedException {
    driver.get(BASE_URL);
    String email = "jsemdospelyclovek@nebudutadypsat.tvojemama";
    driver.findElement(By.name("email")).sendKeys(email);
    driver.findElement(By.xpath("/html/body/nav/div/ul/li[8]/a")).click();
    driver.navigate().back();
    driver.navigate().forward();
    Assert.assertFalse(driver.findElement(By.xpath("/html/body/div/div/div/label[1]/input")).isSelected());
    Assert.assertFalse(driver.findElement(By.xpath("/html/body/div/div/div/label[2]/input")).isSelected());
    driver.findElement(By.xpath("/html/body/div/div/div/label[1]/input")).click();
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/label[1]/input")).isSelected());
    Assert.assertFalse(driver.findElement(By.xpath("/html/body/div/div/div/label[2]/input")).isSelected());
    driver.findElement(By.xpath("/html/body/div/div/div/label[2]/input")).click();
    Assert.assertFalse(driver.findElement(By.xpath("/html/body/div/div/div/label[1]/input")).isSelected());
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/label[2]/input")).isSelected());
  }

  @Test
  public void navigaceRefresh() throws InterruptedException {
    driver.get("https://furbo.sk/playground/clickmebaby.php");
    for (int i = 1; i < 6; i++) {
      driver.findElement(By.id("clickMe")).click();
    }
    driver.navigate().refresh();
    Assert.assertEquals("Iniciální počet kliků", "0", driver.findElement(By.id("clicks")).getText());
    //System.out.println(driver.findElement(By.cssSelector(".description")).getText());
    Assert.assertEquals("klikov", driver.findElement(By.xpath("/html/body/div/div[2]/p")).getText());

  }

  @After
  public void tearDown() {
    driver.quit();
    }
  }

