// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class RedAlertPart {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/redalert.php";
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void RedAlertTestAlert1() {
    driver.get(BASE_URL);
    driver.findElement(By.id("alert1")).click();
    Alert alert = driver.switchTo().alert();
    alert.accept();
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/h1")).getText().contains("Kirov Reporting"));

  }

  @Test
  public void RedAlertTestAlert2() {
    driver.get(BASE_URL);
    driver.findElement(By.id("alert2")).click();
    Alert alert2 = driver.switchTo().alert();
    alert2.dismiss();
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/h1")).getText().contains("Negative"));


  }

  @Test
  public void RedAlertTestAlert3() {
    driver.get(BASE_URL);
    driver.findElement(By.id("alert3")).click();
    Alert alert3 = driver.switchTo().alert();
    alert3.sendKeys("Simon");
    alert3.accept();
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/h1")).getText().contains("Simon"));


  }

  @After
  public void tearDown() {
    //driver.quit();
  }

  }

