// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.util.*;

public class VerifyPageTitle {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final String BASE_URL = "https://furbo.sk/playground/vybersi.php";

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void verifyTitle() {
    driver.get(BASE_URL);
    List<WebElement> pages = driver.findElements(By.xpath("/html/body/nav/div/ul/li/a"));
    List<String> pageUrls = new ArrayList<>();

    for (WebElement page : pages) {
      pageUrls.add(page.getAttribute("href"));
    }
    for (String pageUrl : pageUrls){
      driver.get(pageUrl);
      String expectedTitle = pageUrl.substring(pageUrl.lastIndexOf("/")+1,pageUrl.indexOf(".php"));
      Assert.assertTrue(driver.getTitle().contains(expectedTitle.substring(0,1).toUpperCase()+expectedTitle.substring(1)));
      //System.out.println(expectedTitle.substring(0,1).toUpperCase()+expectedTitle.substring(1));
    }

  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
