// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

public class WaitingForElement {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/zjavenie.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void waitForElementZpusobViaJavaThread() throws InterruptedException {
    driver.get(BASE_URL);
    driver.findElement(By.id("showHim")).click();
    Thread.sleep(3000);
    Assert.assertTrue(driver.findElement(By.xpath("/html/body/div/div/div/img")).isEnabled());
    Assert.assertTrue(driver.findElement(By.id("hideHim")).getText().contains("PREC S DIABLOM !!!"));
  }

  @Test
  public void waitForElementZpusobDynamicky() throws InterruptedException {

    driver.get(BASE_URL);
    driver.findElement(By.id("showHim")).click();

    //příští metoda mi nejede protože timeout očekává datový typ duration ale já tam mám int a nevím jak vyřešit
    //new WebDriverWait(driver,5).until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/div/div/img")));
    Assert.assertEquals(driver.findElement(By.xpath("By.xpath(\"/html/body/div/div/div/img\")).getText()")).getText(),"PREC S DIABLOM !!!");
  }

  @After
  public void tearDown() {
    driver.quit();
    }
  }

