// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.Map;

public class CalcComplete {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final String BASE_URL = "https://furbo.sk/playground/kalkulacka.php";

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    driver.get(BASE_URL);
    driver.manage().window().maximize();
  }

  @Test
  public void calcSum() {

  }

  @After
  public void tearDown() {
    driver.close();
    driver.quit();
  }
}