// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class ClickMeBabyForiDry {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/clickmebaby.php";
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void clickCountPlusOne() {
    driver.get(BASE_URL);
    Assert.assertEquals("Iniciální počet kliků","0",driver.findElement(By.id("clicks")).getText());

    for (int i = 1; i < 11; i++) {
      driver.findElement(By.id("clickMe")).click();
      Assert.assertEquals(String.valueOf(i),driver.findElement(By.id("clicks")).getText());
    }

  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
