// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class Navigace {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/index.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void navigaceIsThisNavigationClassActive() throws InterruptedException {
    driver.get(BASE_URL+"/zjavenie.php");
    driver.findElement(By.xpath("//li[a/@href='zjavenie.php']")).getAttribute("class");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='zjavenie.php']")).getAttribute("class").contains("active"));
  }

  @Test
  public void navigaceCheckAllTabs() throws InterruptedException {
    driver.get(BASE_URL+"/clickmebaby.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='clickmebaby.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/vybersi.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='vybersi.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/tabulka.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='tabulka.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/redalert.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='redalert.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/zjavenie.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='zjavenie.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/kalkulacka.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='kalkulacka.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/xpathtrainingcenter.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='xpathtrainingcenter.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/zenaalebomuz.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='zenaalebomuz.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/registracia.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='registracia.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/moveme.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='moveme.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/stroopeffect.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='stroopeffect.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/nemenne.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='nemenne.php']")).getAttribute("class").contains("active"));
    Thread.sleep(500);
    driver.get(BASE_URL+"/semafor.php");
    Assert.assertTrue(driver.findElement(By.xpath("//li[a/@href='semafor.php']")).getAttribute("class").contains("active"));
    Thread.sleep(1500);
  }


  @After
  public void tearDown() {
    driver.quit();
    }
  }

