// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.awt.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StroopEffect {
  private WebDriver driver;
  private Map<String, Object> vars;
  private final String BASE_URL = "https://furbo.sk/playground/stroopeffect.php";
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void stroopVerifyColor() throws InterruptedException {
    driver.get(BASE_URL);
    List<WebElement> titles = driver.findElements(By.xpath("//html/body/div[2]/h1"));
    for (WebElement title : titles) {
      System.out.println(title.getText());
      System.out.println(title.getCssValue("color"));



    }

    //System.out.println(driver.findElement(By.xpath("/html/body/div[2]/h1[1]")).getText());
    //System.out.println(driver.findElement(By.xpath("/html/body/div[2]/h1[2]")).getText());
    //System.out.println(driver.findElement(By.xpath("/html/body/div[2]/h1[3]")).getText());
    //System.out.println(driver.findElement(By.xpath("/html/body/div[2]/h1[4]")).getText());
    //System.out.println(driver.findElement(By.xpath("/html/body/div[2]/h1[5]")).getCssValue("color"));
  }




  @After
  public void tearDown() {
    driver.quit();
    }
  }

