// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TableVerify {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final String BASE_URL = "https://furbo.sk/playground/tabulka.php";

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void tableFindLastRow() {
    driver.get(BASE_URL);
    //cyklus který najde počet řádků v tabulce
    int rows = Integer.parseInt(driver.findElement(By.xpath("//table/tbody/tr[last()]/td[1]")).getText());
    for (int i = 1; i < rows+1; i++) {

    }

  }

  @Test
  public void tableVerifyNoCulummIsEmpty() {
    driver.get(BASE_URL);
    //projde všechny elementy v tabulce a ověří, že žádní není prázdný
    int rows = Integer.parseInt(driver.findElement(By.xpath("//table/tbody/tr[last()]/td[1]")).getText());
    for (int i = 1; i < rows+1; i++) {
      Assert.assertFalse(driver.findElement(By.xpath("//table/tbody/tr["+i+"]/td[1]")).getText().isEmpty());
      Assert.assertFalse(driver.findElement(By.xpath("//table/tbody/tr["+i+"]/td[2]")).getText().isEmpty());
      Assert.assertFalse(driver.findElement(By.xpath("//table/tbody/tr["+i+"]/td[3]")).getText().isEmpty());
      Assert.assertFalse(driver.findElement(By.xpath("//table/tbody/tr["+i+"]/td[4]")).getText().isEmpty());
    }

  }

  @Test
  public void tableVerifyNoSimonNameUsed() {
    driver.get(BASE_URL);
    //projde všechny křestní jména v tabulce a ověří, že se nikdo nejmenuje Simon
    int rows = Integer.parseInt(driver.findElement(By.xpath("//table/tbody/tr[last()]/td[1]")).getText());
    for (int i = 1; i < rows+1; i++) {
      Assert.assertFalse(driver.findElement(By.xpath("//table/tbody/tr["+i+"]/td[2]")).getText().contains("Simon"));
    }

  }

  @Test
  public void tableFindElementsAndSaveIntoList() {
    //projde všechny elementy v tabulce a uloží je do listu
    driver.get(BASE_URL);
      List<WebElement> rows1 = driver.findElements(By.xpath("//table/tbody/tr"));
    for (WebElement row : rows1) {
      System.out.println(row.getText());
      }
    }

  @Test
  public void tableFindElementsAndSaveIntoListVerifyNoSimonNameUsed() {
    //projde všechny elementy v tabulce a uloží je do listu, projde list a ověří, že nikde není Simon
    driver.get(BASE_URL);
    List<WebElement> rows1 = driver.findElements(By.xpath("//table/tbody/tr"));
    for (WebElement row : rows1) {
      Assert.assertFalse(row.findElement(By.xpath("./td[2]")).getText().contains("Simon"));
    }
  }


  @After
  public void tearDown() {
    driver.quit();
  }
}
